name: Build and Test Container

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - "README.md"

env:
  PROJECT_NAME: tdd-docker-project
  IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/${PROJECT_NAME}

jobs:
  # Build a container and push it to the Docker registry
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout the repo
      uses: actions/checkout@v2
    -
      name: Setup up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Setup up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile.prod
        push: true
        tags: $IMAGE:latest

  # Use the image from the above to run tests in the container
  test:
    runs-on: ubuntu-latest
    # our latest container to be used as a runner
    container: $IMAGE:latest
    # this defines extra services our container will need - like a postgredb
    services:
      # label for service container access
      postgres:
        image: postgres
        env:
          POSTGRES_DB: users
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: runner
          DATABASE_TEST_URL: postgresql://runner:runner@postgres:5432/users
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    -
      name: Checkout the repo
      uses: actions/checkout@v2
    -
      name: Setup up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Run tests
      run: |
        pytest "src/tests" -p no:warnings
        flake8 src
        black src --check
        isort src --check-only

